language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: releases
  api_key:
    secure: XA48DAWUA0nr3BERDgbUM5E7qL9dY2DVvxxiE9yZE9Y5Hz3UwJjH5x+nX60qcdI+TP8KEdNvxi5Ze+Tz/yN0hXdtTbpm0ZfQdvHlRuJTu+rmw0L7r/GLImqzdUPdzCvRn/b8EEL8ToD5N8DzhX4dszT3a9jXtP+CcLzATzV5g9QATjBsBxyaVT8DkzqirRer5fXvHljj2swGbSDYxlw8rxppTRm8TDcljWkm75Y4lGYZHIZT0lNgA0C9t4+5T0Z4tZwDZvTXUlPr4S+2KczNOG+4Mwn+aT0O1fe4awmJe5at/gJCcrKgqJWLuZADxyE/B/fAcrzNp02tUhIYTGRc9H1mDcwPW1fmAS2MBypH9xfGbUUMR7uo1SOSunzqvkE/DuQ5Hd5siS4H5Drz7ENtHIfa12TlmrTrB6zn8hefsA5zXufog6E5DJbquklPzOvtDi2gQ3RyVTqFP1Re5zrCa25g7lS7ZpDEnRIynSTFXUcybgT81l8+WbN2i6qSmq8V0LHHMhlswl3KEzwq689CKqVcOTr3BSUvXGUqeBJhMPhtwyPr23aIzIz/Z/C1eY9eNkpdAuzcjDAxmpPL1r6qSb8gCdOUrUqEqGH6A+2QPfB1sXm87BWc/mXjr4XVRKI8WhjBtwbAoRUNbCNrolBFuXq0EUmBSQD3e/5RfJ8TWQM=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    repo: Tazzie02/pipsi-discord-bot
